name: Axie Auto Snapshot Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn về máy chủ
        uses: actions/checkout@v4

      - name: Cài đặt Node.js môi trường
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Cài đặt thư viện hệ thống cho Puppeteer
        # Các thư viện này giúp Puppeteer chạy được trên môi trường Ubuntu của GitHub
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Cài đặt dependencies của dự án
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth node-fetch

      - name: Khởi động Bot lấy điểm
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
          TOKEN_MOMO: ${{ secrets.TOKEN_MOMO }}
          TOKEN_JAMES1: ${{ secrets.TOKEN_JAMES1 }}
          TOKEN_CRYSITE: ${{ secrets.TOKEN_CRYSITE }}
          TOKEN_CODY: ${{ secrets.TOKEN_CODY }}
          TOKEN_RANDY: ${{ secrets.TOKEN_RANDY }}
          TOKEN_OMI: ${{ secrets.TOKEN_OMI }}
          TOKEN_POKEMON: ${{ secrets.TOKEN_POKEMON }}
          TOKEN_LOKI: ${{ secrets.TOKEN_LOKI }}
        run: node bot.js
